# Generated by Django 4.1 on 2022-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question_and_answer', models.CharField(max_length=1000)),
                ('passcode', models.CharField(max_length=10)),
            ],
        ),
    ]
