# Generated by Django 4.1 on 2022-09-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('completed', models.BooleanField()),
                ('attempts', models.IntegerField()),
                ('question', models.ManyToManyField(to='base.questions')),
            ],
        ),
    ]
