# Generated by Django 4.1 on 2022-09-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usermarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermarks',
            name='question',
        ),
        migrations.AddField(
            model_name='usermarks',
            name='question',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='base.questions'),
            preserve_default=False,
        ),
    ]
