# Generated by Django 4.1 on 2022-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_questions_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
