# Generated by Django 4.1 on 2022-09-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_questions_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('class_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('passcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='passcode',
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ClassUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('highest_difficulty', models.PositiveIntegerField()),
                ('class_completed', models.BooleanField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroom')),
                ('last_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.questions')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='class_id',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='base.classroom'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='classusers',
            constraint=models.UniqueConstraint(fields=('class_id', 'user_id'), name='constrain_classusers'),
        ),
    ]
