# Generated by Django 4.1 on 2022-09-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_classroom_remove_questions_class_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassRoom',
            new_name='ClassRooms',
        ),
    ]
