# Generated by Django 4.1 on 2022-09-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_classroom_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
