# Generated by Django 4.1 on 2022-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_questions_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='correct_questions_required',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
