# Generated by Django 4.1 on 2022-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_classrooms_correct_questions_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='classusers',
            name='completed_questions_per_level',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
