# Generated by Django 4.1 on 2022-09-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_classusers_completed_questions_per_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_and_answer',
            field=models.CharField(max_length=1500),
        ),
    ]
